const state = { module:'home', tab:'', filter:'Weekly', selectedPeriod:'2026-W24', selectedTech:technicians[0].name, assetUpload:[] };
const tabs = {
  reporting:['Executive Overview','Quote Activity','Technician Activity','Financial KPIs','Maintenance Performance','Customer Performance','Margins','Win / Loss','Job Report','Technician Labour','Labour Forecast'],
  contracts:['Dashboard','Contracts','Customers','Proposal Generator','Upcoming Renewals','Expiring Contracts','Settings'],
  employee:['Dashboard','Calendar','Annual Leave','Sick Leave','Apply For Leave','Settings'],
  settings:['Platform Settings']
};
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
const money=n=>'$'+Math.round(n).toLocaleString('en-AU');
function groupRows(filter){
  if(filter==='Weekly') return quoteRows.slice(-52);
  const map={}; quoteRows.forEach(r=>{let key=r.year; let label=String(r.year); if(filter==='Monthly'||filter==='Calendar Month'){key=`${r.year}-${r.month}`;label=`${new Date(2026,r.month-1).toLocaleString('en-AU',{month:'short'})} ${r.year}`} if(filter==='4 Weekly'){key=`${r.year}-P${Math.ceil(Number(r.id.slice(-2))/4)}`;label=`4 Week P${Math.ceil(Number(r.id.slice(-2))/4)} ${r.year}`} if(filter==='Seasonal'){key=`${r.year}-${r.season}`;label=`${r.season} ${r.year}`} if(!map[key]) map[key]={id:key,label,type:filter,jobs:0,quotes:0,value:0,approved:0,outstanding:0,declined:0}; ['jobs','quotes','value','approved','outstanding','declined'].forEach(k=>map[key][k]+=r[k]); });
  return Object.values(map).slice(-48).map(r=>({...r,conversion:Math.round(r.approved/r.value*100)}));
}
function setModule(m){state.module=m; state.tab=tabs[m]?.[0]||''; render();}
$$('.nav').forEach(b=>b.onclick=()=>setModule(b.dataset.module)); $('#closeModal').onclick=()=>$('#modal').classList.add('hidden');
function render(){ $$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.module===state.module)); $('#pageTitle').textContent= state.module==='home'?'Paramount Command Centre': state.module==='reporting'?'Reporting Intelligence': state.module==='contracts'?'Maintenance Contracts':state.module==='employee'?'Employee Portal':'Settings'; renderTabs(); renderContent(); }
function renderTabs(){const t=tabs[state.module]||[]; $('#moduleTabs').innerHTML=t.map(x=>`<button class="tab ${state.tab===x?'active':''}">${x}</button>`).join(''); $$('.tab').forEach(b=>b.onclick=()=>{state.tab=b.textContent;renderContent();renderTabs();});}
function kpi(label,value,note='Click to drill down'){return `<div class="card clickable" onclick="openInfo('${label}')"><div class="kpi-label">${label}</div><div class="kpi-value">${value}</div><div class="kpi-note">${note}</div></div>`}
function openInfo(title,html=''){ $('#modalContent').innerHTML=`<h2>${title}</h2>${html||'<p>This drill-down shows the source records, trend drivers, risk flags and suggested management actions for this KPI.</p><div class="grid grid-3">'+kpi('Current Position','Strong','Above target')+kpi('Needs Attention','3 items','Review this week')+kpi('Recommended Action','Chase approvals','Highest impact')+'</div>'}`; $('#modal').classList.remove('hidden'); }
function renderContent(){ const c=$('#content'); if(state.module==='home') return c.innerHTML=home(); if(state.module==='reporting') return c.innerHTML=reporting(); if(state.module==='contracts') return c.innerHTML=contracts(); if(state.module==='employee') return c.innerHTML=employee(); c.innerHTML=settings(); bindAfterRender(); }
function home(){return `<div class="hero"><div class="card"><p class="eyebrow">Morning Snapshot</p><div class="health">94/100</div><h2>Company health is strong</h2><p class="kpi-note">Revenue, margin and maintenance revenue are trending above target. Quote writing is the main opportunity area this week.</p></div><div class="grid grid-2">${kpi('Revenue This Month',money(482000),'Up 12%')}${kpi('Outstanding Quotes',money(284000),'Chase top 10 sites')}${kpi('Labour Position','+214 hrs','Healthy')}${kpi('Staff Away','4','Leave calendar')}</div></div><div class="section-title"><h2>Management Focus</h2></div><div class="grid grid-3">${kpi('Quote KPI Gap','-38 quotes','Technicians below 1:1')}${kpi('Maintenance Due','42 visits','Next 30 days')}${kpi('Urgent Jobs','7','Require scheduling')}</div>`}
function reporting(){ if(state.tab==='Executive Overview') return executive(); if(state.tab==='Quote Activity') return quoteActivity(); if(state.tab==='Technician Activity') return techActivityView(); if(state.tab==='Job Report') return jobReportView(); if(state.tab==='Technician Labour') return labourView(); if(state.tab==='Labour Forecast') return labourForecast(); return genericReport(state.tab); }
function filters(){return `<div class="filters"><select id="timeFilter" class="control">${['Weekly','Monthly','4 Weekly','Calendar Month','Seasonal','Yearly'].map(x=>`<option ${state.filter===x?'selected':''}>${x}</option>`).join('')}</select></div>`}
function executive(){return `<div class="section-title"><h2>Executive Overview</h2>${filters()}</div><div class="grid grid-4">${kpi('Revenue',money(2485000),'5 year fake data')}${kpi('Quote Conversion','61%','Up 8%')}${kpi('Maintenance Revenue',money(675000),'Up 15%')}${kpi('Technician Utilisation','91%','Target 88%')}</div><div class="grid grid-2" style="margin-top:16px"><div class="card chart-card"><h3>Revenue Trend</h3><canvas id="revenueChart"></canvas></div><div class="card chart-card"><h3>Company Health Breakdown</h3><canvas id="healthChart"></canvas></div></div>`}
function quoteActivity(){const rows=groupRows(state.filter); const last=rows.at(-1); return `<div class="section-title"><h2>Quote Activity - Company Macro View</h2>${filters()}</div><div class="grid grid-4">${kpi('Quotes Generated',last.quotes,'All technicians combined')}${kpi('Jobs Attended',last.jobs,'Quote opportunities')}${kpi('Quote / Job Ratio',(last.quotes/last.jobs).toFixed(2),'Target 1.00')}${kpi('Outstanding Value',money(last.outstanding),'Needs follow-up')}</div><div class="grid grid-2" style="margin-top:16px"><div class="card chart-card"><h3>${state.filter} Quote Trend</h3><canvas id="quoteTrend"></canvas></div><div class="card chart-card"><h3>Approved vs Outstanding</h3><canvas id="approvedTrend"></canvas></div></div><div class="card" style="margin-top:16px"><div class="section-title"><h2>Clickable Time Periods</h2><span class="pill">Click a row to see technician detail</span></div><table><thead><tr><th>Period</th><th>Quotes</th><th>Jobs</th><th>Ratio</th><th>Quote Value</th><th>Approved</th><th>Outstanding</th><th>Conversion</th></tr></thead><tbody>${rows.slice(-20).reverse().map(r=>`<tr onclick="periodDrill('${r.id||r.label}')"><td>${r.label}</td><td>${r.quotes}</td><td>${r.jobs}</td><td>${(r.quotes/r.jobs).toFixed(2)}</td><td>${money(r.value)}</td><td>${money(r.approved)}</td><td>${money(r.outstanding)}</td><td>${r.conversion}%</td></tr>`).join('')}</tbody></table></div><div class="card" style="margin-top:16px"><h2>Customer Ranking - Outstanding vs Approved</h2><table><thead><tr><th>Customer</th><th>Outstanding Quotes</th><th>Approved Quotes</th><th>Outstanding $</th><th>Approved $</th><th>Action</th></tr></thead><tbody>${customers.slice(0,12).map((x,i)=>`<tr><td>${x}</td><td>${seededNumber(i,2,17)}</td><td>${seededNumber(i+5,4,24)}</td><td>${money(seededNumber(i+10,8000,78000))}</td><td>${money(seededNumber(i+20,12000,120000))}</td><td><span class="status ${i<4?'bad':'good'}">${i<4?'Chase':'Healthy'}</span></td></tr>`).join('')}</tbody></table></div>`}
function techActivityView(){const data=techActivity.filter(x=>x.period==='2026-W24'); const selected=data.find(x=>x.technician===state.selectedTech)||data[0]; return `<div class="section-title"><h2>Technician Activity</h2><div class="filters"><select id="techSelect" class="control">${technicians.map(t=>`<option ${state.selectedTech===t.name?'selected':''}>${t.name}</option>`).join('')}</select>${filters()}</div></div><div class="grid grid-4">${kpi('Jobs Attended',selected.jobs,'Service + maintenance')}${kpi('Maintenance Visits',selected.maintenance,'Attended')}${kpi('Quotes Written',selected.quotes,'KPI target 1 per job')}${kpi('Quote / Job Ratio',selected.ratio,'Target 1.00')}</div><div class="grid grid-2" style="margin-top:16px"><div class="card chart-card"><h3>Jobs vs Quotes Benchmark</h3><canvas id="techBench"></canvas></div><div class="card chart-card"><h3>Peer Ranking</h3><canvas id="peerRank"></canvas></div></div><div class="card" style="margin-top:16px"><h2>Company KPI Explanation</h2><p>${selected.technician} attended <strong>${selected.jobs}</strong> jobs and wrote <strong>${selected.quotes}</strong> quotes. The company KPI is <strong>1 quote for every 1 job</strong>. ${selected.ratio>=1?'<span class="good">This technician is meeting target.</span>':'<span class="bad">This technician needs support to capture more quote opportunities.</span>'}</p><table><thead><tr><th>Technician</th><th>Jobs</th><th>Quotes</th><th>Ratio</th><th>Quote Value</th><th>Approved</th><th>Conversion</th></tr></thead><tbody>${data.sort((a,b)=>b.ratio-a.ratio).map((r,i)=>`<tr onclick="state.selectedTech='${r.technician}';renderContent()"><td>#${i+1} ${r.technician}</td><td>${r.jobs}</td><td>${r.quotes}</td><td>${r.ratio}</td><td>${money(r.quoteValue)}</td><td>${money(r.approved)}</td><td>${r.conversion}%</td></tr>`).join('')}</tbody></table></div>`}
function periodDrill(id){const data=techActivity.filter(x=>x.period==='2026-W24'); openInfo(`Period Drill Down: ${id}`,`<p>Technician activity for the selected period. This lets managers see who created the quotes during that week/month/season.</p><table><thead><tr><th>Technician</th><th>Jobs</th><th>Maintenance</th><th>Service Calls</th><th>Quotes</th><th>Ratio</th><th>Quote Value</th><th>Approved</th></tr></thead><tbody>${data.map(r=>`<tr><td>${r.technician}</td><td>${r.jobs}</td><td>${r.maintenance}</td><td>${r.service}</td><td>${r.quotes}</td><td>${r.ratio}</td><td>${money(r.quoteValue)}</td><td>${money(r.approved)}</td></tr>`).join('')}</tbody></table>`)}
function jobReportView(){return `<div class="section-title"><h2>Job Report</h2><span class="pill">Flags missing data and labour risk</span></div><div class="grid grid-4">${kpi('Outstanding Jobs',jobReport.length,'No rows removed')}${kpi('Flagged For Review',jobReport.filter(j=>j.flagged).length,'Needs attention')}${kpi('Projected Hours',jobReport.reduce((a,b)=>a+b.hours,0),'Excludes projects later')}${kpi('Priority 1','9','Review schedule')}</div><div class="card" style="margin-top:16px"><table><thead><tr><th>Flag</th><th>Account Manager</th><th>Job No</th><th>Customer</th><th>Category</th><th>Price</th><th>Scheduled Date</th><th>Technician</th><th>Status</th><th>Hours</th></tr></thead><tbody>${jobReport.map(j=>`<tr><td>${j.flagged?'<span class="flag"></span>Review':''}</td><td>${j.account}</td><td>${j.job}</td><td>${j.customer}</td><td>${j.category}</td><td>${money(j.price)}</td><td>${j.scheduled||'<span class="bad">Missing</span>'}</td><td>${j.tech}</td><td>${j.status}</td><td>${j.hours}</td></tr>`).join('')}</tbody></table></div><div class="card" style="margin-top:16px"><h2>Changes Made Register</h2><table><thead><tr><th>Date</th><th>Job Number</th><th>Field Changed</th><th>Previous</th><th>New</th><th>Notes</th></tr></thead><tbody><tr><td>2026-06-25</td><td>JOB-26012</td><td>Status</td><td>Not Complete</td><td>Waiting Parts</td><td>Updated after operations review</td></tr><tr><td>2026-06-25</td><td>JOB-26033</td><td>Hours</td><td>0</td><td>8</td><td>Maintenance allowance added</td></tr></tbody></table></div>`}
function labourView(){return `<div class="section-title"><h2>Technician Labour</h2><span class="pill">7:45am - 4:15pm, Mon-Fri</span></div><div class="grid grid-4">${kpi('Remaining Workdays','4','June 2026')}${kpi('Available Hours','896','Adjusted')}${kpi('Booked Hours','682','Confirmed')}${kpi('After Hours Tech','Chris Taylor','Confirm weekly')}</div><div class="card" style="margin-top:16px"><table><thead><tr><th>Technician</th><th>Role</th><th>Standard Hours</th><th>Exceptions</th><th>Available</th><th>Booked</th><th>Balance</th></tr></thead><tbody>${technicians.map((t,i)=>{let av=seededNumber(i+70,70,146),book=seededNumber(i+80,45,132);return `<tr><td>${t.name}</td><td>${t.role}</td><td>8/day</td><td>${t.role==='Apprentice'?'Pairing rule active':'None'}</td><td>${av}</td><td>${book}</td><td class="${av-book>20?'good':'warn'}">${av-book}</td></tr>`}).join('')}</tbody></table></div>`}
function labourForecast(){return `<div class="grid grid-3">${kpi('Projected Labour Balance','+214 hrs','Healthy')}${kpi('Outstanding Job Hours','682 hrs','Projects excluded')}${kpi('Recommendation','Chase quotes','Keep pipeline healthy')}</div><div class="card" style="margin-top:16px"><h2>Action Guidance</h2><p>A projected balance around +200 hours is healthy. Current recommendation is to chase outstanding approved work, keep priority service calls scheduled, and review preventative maintenance that can move if urgent labour increases.</p></div>`}
function genericReport(name){return `<div class="section-title"><h2>${name}</h2>${filters()}</div><div class="grid grid-4">${kpi('Current Month',money(125000),'Sample data')}${kpi('Year Trend','Up 9%','5 years')}${kpi('Needs Attention','4','Drill down')}${kpi('Action','Review top sites','Management focus')}</div><div class="grid grid-2" style="margin-top:16px"><div class="card chart-card"><h3>${name} Trend</h3><canvas id="genericChart"></canvas></div><div class="card"><h3>Management Summary</h3><p>This page is structured for decision making and is ready to connect to Supabase and Simpro.</p></div></div>`}
function contracts(){ if(state.tab==='Proposal Generator') return proposal(); if(state.tab==='Customers') return customersView(); return contractsDashboard(); }
function contractsDashboard(){return `<div class="grid grid-4">${kpi('Active Contracts','64','Under management')}${kpi('Expiring 30 Days','7','Renewal risk')}${kpi('Revenue Under Contract',money(1320000),'Annualised')}${kpi('Average Contract Value',money(20625),'Across portfolio')}</div><div class="card" style="margin-top:16px"><h2>Upcoming Renewals</h2><table><thead><tr><th>Customer</th><th>Site</th><th>Annual Value</th><th>Expiry</th><th>Status</th></tr></thead><tbody>${contractCustomers.slice(0,12).map((c,i)=>`<tr><td>${c.name}</td><td>${c.site}</td><td>${money(c.value)}</td><td>${c.expiry}</td><td><span class="${i<4?'warn':'good'}">${i<4?'Prepare Renewal':'Active'}</span></td></tr>`).join('')}</tbody></table></div>`}
function customersView(){return `<div class="section-title"><h2>Customers - Alphabetical</h2><span class="pill">Click customer to open assets</span></div><div class="card"><table><thead><tr><th>Customer</th><th>Site</th><th>Assets</th><th>Contract Value</th><th>Expiry</th></tr></thead><tbody>${contractCustomers.map(c=>`<tr onclick="openCustomer('${c.name}')"><td>${c.name}</td><td>${c.site}</td><td>${c.assets.length}</td><td>${money(c.value)}</td><td>${c.expiry}</td></tr>`).join('')}</tbody></table></div>`}
function openCustomer(name){const c=contractCustomers.find(x=>x.name===name);openInfo(name,`<p><strong>Site:</strong> ${c.site}<br><strong>Annual value:</strong> ${money(c.value)}<br><strong>Expiry:</strong> ${c.expiry}</p><h3>Assets</h3><table><thead><tr><th>Asset ID</th><th>Type</th><th>Location</th><th>Age</th></tr></thead><tbody>${c.assets.map(a=>`<tr><td>${a.id}</td><td>${a.type}</td><td>${a.location}</td><td>${a.age} years</td></tr>`).join('')}</tbody></table>`)}
function proposal(){return `<div class="section-title"><h2>Proposal Generator</h2><span class="pill">No preview. Immediate PDF download.</span></div><div class="grid grid-2"><div class="card"><div class="form"><label>Customer Details Upload</label><input type="file" id="customerUpload" accept=".csv,.xlsx"><label>Customer Name</label><input id="proposalCustomer" value="Monash Corporate Park"><label>Site Details</label><textarea id="proposalSite">Building A, 22 Corporate Drive, Melbourne VIC</textarea><label>Contract Length</label><select id="contractLength"><option>12 months</option><option>24 months</option><option>36 months</option></select><label>Visit Frequency</label><select id="visitFrequency"><option value="2">Bi-Annual</option><option value="4" selected>Quarterly</option><option value="12">Monthly</option></select><label>Response Time</label><select id="responseTime"><option value="1">Standard</option><option value="1.15">Priority</option><option value="1.3">Emergency</option></select></div></div><div class="card"><h3>Asset List Upload</h3><input type="file" id="assetUpload" accept=".csv"><p class="kpi-note">Upload CSV, manually edit below, then download the asset list as CSV.</p><div id="assetEditor"></div><button class="btn secondary" onclick="addAssetRow()">Add Asset</button> <button class="btn secondary" onclick="downloadAssets()">Download CSV</button><hr><div class="kpi-label">Calculated Annual Contract Value</div><div id="calculatedPrice" class="kpi-value">$0</div><button class="btn" onclick="generateProposalPDF()">Generate Proposal PDF</button></div></div>`}
function defaultAssets(){state.assetUpload=[{type:'Package Unit',qty:4,age:8},{type:'Split System',qty:12,age:4},{type:'Exhaust Fan',qty:8,age:6},{type:'Ducted System',qty:3,age:10}]}
function renderAssetEditor(){if(!state.assetUpload.length)defaultAssets(); const el=$('#assetEditor'); if(!el) return; el.innerHTML=state.assetUpload.map((a,i)=>`<div class="asset-row"><select onchange="state.assetUpload[${i}].type=this.value;renderAssetEditor()">${assets.map(x=>`<option ${x.type===a.type?'selected':''}>${x.type}</option>`).join('')}</select><input type="number" value="${a.qty}" onchange="state.assetUpload[${i}].qty=+this.value;renderAssetEditor()"><input type="number" value="${a.age}" onchange="state.assetUpload[${i}].age=+this.value;renderAssetEditor()"><button class="btn secondary" onclick="state.assetUpload.splice(${i},1);renderAssetEditor()">×</button></div>`).join(''); $('#calculatedPrice').textContent=money(calculateContractPrice());}
function calculateContractPrice(){const visits=+($('#visitFrequency')?.value||4); const response=+($('#responseTime')?.value||1); let base=state.assetUpload.reduce((sum,a)=>{const r=assets.find(x=>x.type===a.type)||assets[0]; const ageRisk=a.age>10?1.2:a.age>6?1.1:1; return sum + r.rate*a.qty*ageRisk*(visits/4);},0); return base*response*1.28;}
function addAssetRow(){state.assetUpload.push({type:'Split System',qty:1,age:1});renderAssetEditor()}
function downloadAssets(){const csv='Type,Quantity,Age\n'+state.assetUpload.map(a=>`${a.type},${a.qty},${a.age}`).join('\n');downloadFile(csv,'paramount-asset-list.csv','text/csv')}
function downloadFile(content,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function generateProposalPDF(){const { jsPDF }=window.jspdf; const doc=new jsPDF(); const customer=$('#proposalCustomer').value; const price=money(calculateContractPrice()); let y=18; doc.setFontSize(22); doc.text('Paramount Air Maintenance Proposal',14,y); y+=14; doc.setFontSize(12); doc.text(`Prepared for: ${customer}`,14,y); y+=8; doc.text(`Calculated Annual Contract Value: ${price}`,14,y); y+=14; ['Company Profile','Maintenance Methodology','Asset Register','Visit Schedule','Service Inclusions','Exclusions','Compliance & Safety','Commercial Terms','Signature Acceptance'].forEach(section=>{doc.setFontSize(15);doc.text(section,14,y);y+=7;doc.setFontSize(10);doc.text('Paramount Air will provide planned preventative maintenance, asset condition reporting, risk identification, compliance support and responsive HVAC service delivery tailored to the customer site.',14,y,{maxWidth:180});y+=20;if(y>270){doc.addPage();y=18;}}); doc.save(`Paramount-Maintenance-Proposal-${customer.replaceAll(' ','-')}.pdf`)}
function employee(){ if(state.tab==='Calendar') return leaveCalendar(); if(state.tab==='Annual Leave') return annualLeave(); if(state.tab==='Sick Leave') return sickLeave(); if(state.tab==='Apply For Leave') return applyLeave(); return employeeDashboard(); }
function employeeDashboard(){return `<div class="grid grid-4">${kpi('Currently On Leave','3','Today')}${kpi('Upcoming Leave','14','Next 30 days')}${kpi('Pending Requests','5','Awaiting manager')}${kpi('Birthdays','2','This month')}</div><div class="grid grid-2" style="margin-top:16px"><div class="card">${leaveCalendar()}</div><div class="card"><h2>Public Holidays</h2><p>Kings Birthday, Melbourne Cup, Christmas Day and Boxing Day are included in the fake calendar data.</p></div></div>`}
function leaveCalendar(){return `<h2>Team Calendar</h2><div class="calendar">${Array.from({length:35},(_,i)=>`<div class="day"><strong>${i+1<=30?i+1:''}</strong>${[3,7,12,18,23,27].includes(i)?`<span class="leave-chip">${leaveEmployees[i%leaveEmployees.length].name} - Annual</span>`:''}${[9,21].includes(i)?`<span class="leave-chip">Sick Leave</span>`:''}</div>`).join('')}</div>`}
function annualLeave(){return `<div class="section-title"><h2>Annual Leave Register</h2><span class="pill">Graphs restored for V3</span></div><div class="grid grid-2"><div class="card chart-card"><h3>Entitlement vs Taken</h3><canvas id="leaveChart"></canvas></div><div class="card chart-card"><h3>Remaining Leave</h3><canvas id="remainingLeave"></canvas></div></div><div class="card" style="margin-top:16px"><table><thead><tr><th>Employee</th><th>Entitlement</th><th>Taken</th><th>Booked</th><th>Remaining</th></tr></thead><tbody>${leaveEmployees.map(e=>`<tr><td>${e.name}</td><td>${e.entitlement}</td><td>${e.taken}</td><td>${e.booked}</td><td>${e.entitlement-e.taken-e.booked}</td></tr>`).join('')}</tbody></table></div>`}
function sickLeave(){return `<div class="card"><h2>Sick Leave</h2><table><thead><tr><th>Employee</th><th>Sick Leave Taken</th><th>Trend</th></tr></thead><tbody>${leaveEmployees.map(e=>`<tr><td>${e.name}</td><td>${e.sick} hrs</td><td>${e.sick>38?'<span class="warn">Review pattern</span>':'Normal'}</td></tr>`).join('')}</tbody></table></div>`}
function applyLeave(){return `<div class="card"><h2>Apply For Leave</h2><div class="form"><label>Request Type</label><select><option>Annual Leave</option><option>Sick Leave</option><option>Carer's Leave</option><option>Long Service Leave</option></select><label>Start Date</label><input type="date"><label>End Date</label><input type="date"><label>Half Day</label><select><option>No</option><option>Morning</option><option>Afternoon</option></select><label>Notes</label><textarea></textarea><label>Attach Document</label><input type="file"><button class="btn">Submit Request</button></div></div>`}
function settings(){return `<div class="card"><h2>V3 Platform Settings</h2><ul class="settings-list"><li>Roles: Managers and Admin.</li><li>Managers approve leave, generate proposals, edit contract data and view financials.</li><li>Supabase-ready tables: customers, sites, contacts, assets, contracts, pricing rules, employees, leave requests, jobs, quotes, labour, KPI history and change register.</li></ul></div>`}
function bindAfterRender(){ const tf=$('#timeFilter'); if(tf) tf.onchange=e=>{state.filter=e.target.value;renderContent();setTimeout(drawCharts,0)}; const ts=$('#techSelect'); if(ts) ts.onchange=e=>{state.selectedTech=e.target.value;renderContent();setTimeout(drawCharts,0)}; const au=$('#assetUpload'); if(au) au.onchange=e=>{const file=e.target.files[0]; if(!file)return; const reader=new FileReader(); reader.onload=()=>{state.assetUpload=reader.result.split(/\r?\n/).slice(1).filter(Boolean).map(line=>{const [type,qty,age]=line.split(',');return{type:type||'Split System',qty:+qty||1,age:+age||1}}); renderAssetEditor();}; reader.readAsText(file);}; ['visitFrequency','responseTime'].forEach(id=>{const x=$('#'+id); if(x)x.onchange=renderAssetEditor}); renderAssetEditor(); drawCharts();}
function chart(id,type,labels,datasets){const ctx=$('#'+id); if(!ctx)return; new Chart(ctx,{type,data:{labels,datasets},options:{responsive:true,plugins:{legend:{labels:{color:'#dbe9fb',font:{size:14}}}},scales:{x:{ticks:{color:'#dbe9fb',font:{size:12}},grid:{color:'rgba(255,255,255,.08)'}},y:{ticks:{color:'#dbe9fb',font:{size:12}},grid:{color:'rgba(255,255,255,.08)'}}}}})}
function drawCharts(){const rows=groupRows(state.filter).slice(-12); chart('revenueChart','line',rows.map(r=>r.label),[{label:'Revenue',data:rows.map(r=>r.value)}]); chart('healthChart','bar',['Revenue','Quotes','Maintenance','Utilisation'],[{label:'Score',data:[94,88,96,91]}]); chart('quoteTrend','line',rows.map(r=>r.label),[{label:'Quotes',data:rows.map(r=>r.quotes)},{label:'Jobs',data:rows.map(r=>r.jobs)}]); chart('approvedTrend','bar',rows.map(r=>r.label),[{label:'Approved',data:rows.map(r=>r.approved)},{label:'Outstanding',data:rows.map(r=>r.outstanding)}]); const data=techActivity.filter(x=>x.period==='2026-W24'); chart('techBench','bar',['Jobs','Quotes','Target KPI'],[{label:state.selectedTech,data:[data.find(x=>x.technician===state.selectedTech)?.jobs||0,data.find(x=>x.technician===state.selectedTech)?.quotes||0,data.find(x=>x.technician===state.selectedTech)?.jobs||0]}]); chart('peerRank','bar',data.map(x=>x.technician.split(' ')[0]),[{label:'Quote / Job Ratio',data:data.map(x=>x.ratio)},{label:'Company KPI',data:data.map(()=>1)}]); chart('genericChart','line',rows.map(r=>r.label),[{label:'Trend',data:rows.map(r=>r.approved)}]); chart('leaveChart','bar',leaveEmployees.map(e=>e.name.split(' ')[0]),[{label:'Entitlement',data:leaveEmployees.map(e=>e.entitlement)},{label:'Taken',data:leaveEmployees.map(e=>e.taken)}]); chart('remainingLeave','bar',leaveEmployees.map(e=>e.name.split(' ')[0]),[{label:'Remaining',data:leaveEmployees.map(e=>e.entitlement-e.taken-e.booked)}]);}
render(); setTimeout(drawCharts,0);
