const state = { module:'home', tab:'', filter:'Weekly', selectedTech:'Chris Taylor', selectedPeriod:'2026-W24', assets:[] };
const tabs = {
  reporting:['Executive Overview','Quote Activity','Technician Activity','Financial KPIs','Maintenance Performance','Customer Performance','Margins','Win / Loss','Job Report','Technician Labour','Labour Forecast'],
  contracts:['Dashboard','Contracts','Customers','Proposal Generator','Upcoming Renewals','Expiring Contracts','Settings'],
  employee:['Dashboard','Calendar','Annual Leave','Sick Leave','Apply For Leave','Settings'],
  settings:['Platform Settings']
};
const $ = q => document.querySelector(q);
const $$ = q => Array.from(document.querySelectorAll(q));
const money = n => '$' + Math.round(n).toLocaleString('en-AU');
const sum = (arr,k) => arr.reduce((a,b)=>a+(+b[k]||0),0);
function periodRows(){
  if(state.filter==='Weekly') return quoteWeeks.slice(-52);
  const map = {};
  quoteWeeks.forEach(r=>{
    let key=String(r.year), label=String(r.year);
    if(state.filter==='Monthly'||state.filter==='Calendar Month'){ key=`${r.year}-${r.month}`; label=`${new Date(2026,r.month-1).toLocaleString('en-AU',{month:'short'})} ${r.year}`; }
    if(state.filter==='4 Weekly'){ key=`${r.year}-P${Math.ceil(r.week/4)}`; label=`4 Week P${Math.ceil(r.week/4)} ${r.year}`; }
    if(state.filter==='Seasonal'){ key=`${r.season}-${r.year}`; label=`${r.season} ${r.year}`; }
    if(!map[key]) map[key]={id:key,label,year:r.year,jobs:0,quotes:0,value:0,approved:0,outstanding:0,declined:0};
    ['jobs','quotes','value','approved','outstanding','declined'].forEach(k=>map[key][k]+=r[k]);
  });
  return Object.values(map).map(r=>({...r,conversion:Math.round((r.approved/r.value)*100)})).slice(-60);
}
function setModule(module){ state.module=module; state.tab=tabs[module]?.[0]||''; render(); }
$$('.side-link').forEach(b=>b.addEventListener('click',()=>setModule(b.dataset.module)));
$('#close-drawer').addEventListener('click',()=>$('#drawer').classList.add('hidden'));
function render(){
  $$('.side-link').forEach(b=>b.classList.toggle('active', b.dataset.module===state.module));
  $('#page-title').textContent = state.module==='home'?'Paramount Command Centre':state.module==='reporting'?'Reporting Intelligence':state.module==='contracts'?'Maintenance Contracts':state.module==='employee'?'Employee Portal':'Settings';
  renderTabs(); renderScreen();
}
function renderTabs(){
  const list=tabs[state.module]||[];
  $('#module-tabs').innerHTML=list.map(t=>`<button class="tab ${state.tab===t?'active':''}" data-tab="${t}">${t}</button>`).join('');
  $$('.tab').forEach(b=>b.addEventListener('click',()=>{state.tab=b.dataset.tab; renderTabs(); renderScreen();}));
}
function kpi(label,value,note='Click for detail'){ return `<div class="card clickable" onclick="openDrawer('${label}')"><div class="kpi-label">${label}</div><div class="kpi-value">${value}</div><div class="kpi-note">${note}</div></div>`; }
function openDrawer(title, body=''){
  $('#drawer-content').innerHTML = `<h2>${title}</h2><div style="height:12px"></div>${body || `<div class="summary-box">This drill-down is designed to show source records, trend drivers, accountable owners and recommended management actions.</div><div style="height:16px"></div><div class="grid grid-3">${kpi('Current Position','Strong','Above target')}${kpi('Attention Needed','3 items','Review this week')}${kpi('Next Action','Chase approvals','Highest impact')}</div>`}`;
  $('#drawer').classList.remove('hidden');
}
function timeFilter(){return `<div class="filters"><select id="time-filter" class="control">${['Weekly','Monthly','4 Weekly','Calendar Month','Seasonal','Yearly'].map(x=>`<option ${state.filter===x?'selected':''}>${x}</option>`).join('')}</select></div>`}
function renderScreen(){
  const s=$('#screen');
  if(state.module==='home') s.innerHTML=home();
  if(state.module==='reporting') s.innerHTML=reporting();
  if(state.module==='contracts') s.innerHTML=contracts();
  if(state.module==='employee') s.innerHTML=employee();
  if(state.module==='settings') s.innerHTML=settings();
  bind();
}
function home(){return `<div class="hero"><div class="card soft clickable" onclick="state.module='reporting';state.tab='Executive Overview';render()"><p class="eyebrow">Morning Snapshot</p><div class="health-score">94</div><h2>Company health is strong.</h2><p class="kpi-note">Revenue, maintenance revenue and utilisation are above target. Quote writing is the biggest opportunity this week.</p></div><div class="grid grid-2">${kpi('Revenue This Month',money(482000),'Up 12%')}${kpi('Outstanding Quotes',money(284000),'Chase top sites')}${kpi('Labour Position','+214 hrs','Healthy')}${kpi('Staff Away','4','Check leave')}</div></div><div class="section-head"><h2>Command Centre</h2></div><div class="grid grid-3"><div class="card clickable" onclick="state.module='reporting';state.tab='Quote Activity';render()"><h3>Reporting Intelligence</h3><p class="kpi-note">Executive KPIs, quote activity, technician activity, job reports and labour forecasting.</p></div><div class="card clickable" onclick="state.module='contracts';state.tab='Proposal Generator';render()"><h3>Maintenance Contracts</h3><p class="kpi-note">Customer sites, assets, renewals and premium maintenance proposal generation.</p></div><div class="card clickable" onclick="state.module='employee';state.tab='Annual Leave';render()"><h3>Employee Portal</h3><p class="kpi-note">Leave calendar, entitlement graphs, sick leave tracking and leave applications.</p></div></div>`;}
function reporting(){
  if(state.tab==='Executive Overview') return executive();
  if(state.tab==='Quote Activity') return quoteActivity();
  if(state.tab==='Technician Activity') return technicianActivity();
  if(state.tab==='Job Report') return jobReport();
  if(state.tab==='Technician Labour') return technicianLabour();
  if(state.tab==='Labour Forecast') return labourForecast();
  return genericReport(state.tab);
}
function executive(){const rows=periodRows().slice(-12);return `<div class="section-head"><h2>Executive Overview</h2>${timeFilter()}</div><div class="hero"><div class="card clickable" onclick="openDrawer('Company Health Score')"><p class="eyebrow">Company Health Score</p><div class="health-score">94/100</div><p class="kpi-note">Revenue +12%, Quote Conversion +8%, Maintenance Revenue +15%, Technician Utilisation 91%.</p></div><div class="grid grid-2">${kpi('Quotes Written',sum(rows,'quotes'))}${kpi('Jobs Completed',sum(rows,'jobs'))}${kpi('Quote Conversion','68%')}${kpi('Technician Utilisation','91%')}</div></div><div class="grid grid-2" style="margin-top:16px"><div class="card chart-wrap"><h3>Revenue Trend</h3>${lineChart(rows.map(r=>r.label),rows.map(r=>r.value),'Revenue')}</div><div class="card chart-wrap"><h3>Health Drivers</h3>${barChart(['Revenue','Quotes','Maintenance','Utilisation'],[94,88,96,91],100)}</div></div>`;}
function quoteActivity(){const rows=periodRows();const recent=rows.slice(-12);return `<div class="section-head"><div><h2>Quote Activity</h2><p class="kpi-note">Macro view of all technicians combined. Click a period to drill into technician output.</p></div>${timeFilter()}</div><div class="grid grid-4">${kpi('Total Quotes',sum(recent,'quotes'))}${kpi('Quote Value',money(sum(recent,'value')))}${kpi('Approved Value',money(sum(recent,'approved')))}${kpi('Outstanding Value',money(sum(recent,'outstanding')))}</div><div class="grid grid-2" style="margin-top:16px"><div class="card chart-wrap"><h3>Quotes vs Jobs</h3>${multiLineChart(recent.map(r=>r.label),[{name:'Quotes',values:recent.map(r=>r.quotes),cls:'line-main'},{name:'Jobs',values:recent.map(r=>r.jobs),cls:'line-accent'}])}</div><div class="card chart-wrap"><h3>Approved vs Outstanding</h3>${groupedBars(recent.map(r=>r.label),recent.map(r=>r.approved),recent.map(r=>r.outstanding))}</div></div><div class="card" style="margin-top:16px"><h3>Periods</h3><table><thead><tr><th>Period</th><th>Jobs</th><th>Quotes</th><th>Ratio</th><th>Quote Value</th><th>Approved</th><th>Outstanding</th></tr></thead><tbody>${rows.slice(-18).reverse().map(r=>`<tr onclick="periodDetail('${r.id}','${r.label}')" class="clickable"><td>${r.label}</td><td>${r.jobs}</td><td>${r.quotes}</td><td>${(r.quotes/r.jobs).toFixed(2)}</td><td>${money(r.value)}</td><td>${money(r.approved)}</td><td>${money(r.outstanding)}</td></tr>`).join('')}</tbody></table></div><div class="card" style="margin-top:16px"><h3>Customer Sites Ranked by Outstanding vs Approved Quotes</h3><table><thead><tr><th>Site</th><th>Outstanding Quotes</th><th>Approved Quotes</th><th>Outstanding $</th><th>Approved $</th><th>Conversion</th></tr></thead><tbody>${customerQuoteRows.slice(0,12).map(c=>`<tr><td>${c.customer}</td><td>${c.outstanding}</td><td>${c.approved}</td><td>${money(c.outstandingValue)}</td><td>${money(c.approvedValue)}</td><td>${c.conversion}%</td></tr>`).join('')}</tbody></table></div>`;}
function periodDetail(id,label){ const rows=technicianRows.filter(r=>id.includes('W')?r.period===id:String(r.year)===String(id).slice(-4)).slice(0,8); openDrawer(`${label} Technician Drill Down`,`<div class="grid grid-4">${kpi('Technicians',rows.length)}${kpi('Jobs',sum(rows,'jobs'))}${kpi('Quotes',sum(rows,'quotes'))}${kpi('KPI Gap',sum(rows,'quotes')-sum(rows,'jobs'))}</div><div class="card" style="margin-top:16px"><table><thead><tr><th>Technician</th><th>Jobs</th><th>Maint.</th><th>Service</th><th>Quotes</th><th>Ratio</th><th>Approved $</th><th>Outstanding $</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.technician}</td><td>${r.jobs}</td><td>${r.maintenance}</td><td>${r.service}</td><td>${r.quotes}</td><td>${r.ratio}</td><td>${money(r.approved)}</td><td>${money(r.outstanding)}</td></tr>`).join('')}</tbody></table></div>`); }
function technicianActivity(){const rows=technicianRows.filter(r=>r.technician===state.selectedTech).slice(-26);const latest=rows[rows.length-1];const peer=technicianRows.filter(r=>r.period===latest.period);return `<div class="section-head"><div><h2>Technician Activity</h2><p class="kpi-note">Select a technician to review jobs, maintenance, service calls, quotes and KPI ratio.</p></div><div class="filters"><select id="tech-select" class="control">${technicians.map(t=>`<option ${state.selectedTech===t.name?'selected':''}>${t.name}</option>`).join('')}</select></div></div><div class="grid grid-4">${kpi('Total Jobs',latest.jobs)}${kpi('Maintenance Visits',latest.maintenance)}${kpi('Service Calls',latest.service)}${kpi('Quotes Written',latest.quotes)}</div><div class="grid grid-4" style="margin-top:16px">${kpi('Quote Value',money(latest.quoteValue))}${kpi('Approved Value',money(latest.approved))}${kpi('Outstanding Value',money(latest.outstanding))}${kpi('Jobs vs Quotes Ratio',latest.ratio,'KPI target is 1.00')}</div><div class="grid grid-2" style="margin-top:16px"><div class="card chart-wrap"><h3>${state.selectedTech}: Jobs vs Quotes</h3>${multiLineChart(rows.map(r=>`W${r.week}`),[{name:'Jobs',values:rows.map(r=>r.jobs),cls:'line-accent'},{name:'Quotes',values:rows.map(r=>r.quotes),cls:'line-main'}])}</div><div class="card chart-wrap"><h3>Peer Benchmark: Quote / Job Ratio</h3>${barChart(peer.map(r=>r.technician.split(' ')[0]),peer.map(r=>r.ratio),1.6,1)}</div></div><div class="card" style="margin-top:16px"><h3>Peer Ranking</h3><table><thead><tr><th>Rank</th><th>Technician</th><th>Jobs</th><th>Quotes</th><th>Ratio</th><th>Company KPI</th><th>Management Note</th></tr></thead><tbody>${peer.sort((a,b)=>b.ratio-a.ratio).map((r,i)=>`<tr><td><span class="rank">${i+1}</span></td><td>${r.technician}</td><td>${r.jobs}</td><td>${r.quotes}</td><td>${r.ratio}</td><td>1 quote / 1 job</td><td>${r.ratio>=1?'<span class="status-good">On target</span>':'<span class="status-warn">Coaching opportunity</span>'}</td></tr>`).join('')}</tbody></table></div>`;}
function genericReport(title){const rows=periodRows().slice(-12);return `<div class="section-head"><h2>${title}</h2>${timeFilter()}</div><div class="grid grid-3">${kpi('Current Month',money(128000))}${kpi('Trend','Up 8%')}${kpi('Needs Attention','4 items')}</div><div class="card chart-wrap" style="margin-top:16px"><h3>${title} Trend</h3>${lineChart(rows.map(r=>r.label),rows.map(r=>r.approved),'Trend')}</div>`;}
function jobReport(){return `<div class="section-head"><h2>Job Report</h2><span class="pill">Flagged jobs, categories and change register</span></div><div class="grid grid-4">${kpi('Total Jobs',jobRows.length)}${kpi('Flagged for Review',jobRows.filter(j=>j.flagged).length)}${kpi('Outstanding Hours',sum(jobRows.filter(j=>j.category!=='PJTS'),'hours'))}${kpi('Changed Items',jobRows.filter(j=>j.changed).length)}</div><div class="card" style="margin-top:16px"><table><thead><tr><th></th><th>Account Manager</th><th>Job Number</th><th>Category</th><th>Job Price</th><th>Scheduled Date</th><th>Technician</th><th>Status</th><th>Hours</th></tr></thead><tbody>${jobRows.slice(0,38).map(j=>`<tr><td>${j.flagged?'<span class="flag-dot"></span>':''}${j.changed?'•':''}</td><td>${j.account}</td><td>${j.job}</td><td>${j.category}</td><td>${money(j.price)}</td><td>${j.scheduled||'<span class="status-bad">Missing</span>'}</td><td>${j.tech}</td><td>${j.status}</td><td>${j.hours}</td></tr>`).join('')}</tbody></table></div><div class="card" style="margin-top:16px"><h3>Changes Made Register</h3><table><thead><tr><th>Date</th><th>Job</th><th>Field</th><th>Previous</th><th>New</th><th>Notes</th></tr></thead><tbody>${jobRows.filter(j=>j.changed).slice(0,8).map(j=>`<tr><td>25 Jun 2026</td><td>${j.job}</td><td>Hours / Status</td><td>Unreviewed</td><td>${j.hours} hrs / ${j.status}</td><td>Update external system</td></tr>`).join('')}</tbody></table></div>`;}
function technicianLabour(){const techs=technicians.map((t,i)=>({name:t.name,available:seeded(i+220,96,168),booked:seeded(i+221,72,152),leave:i%4===0?'Annual Leave':'None'}));return `<div class="section-head"><h2>Technician Labour</h2><span class="pill">Current date: 25 June 2026</span></div><div class="grid grid-3">${kpi('Remaining Workdays','4')}${kpi('After Hours Tech','Chris Taylor')}${kpi('Seasonal Mode','Winter')}</div><div class="card" style="margin-top:16px"><table><thead><tr><th>Technician</th><th>Available Hours</th><th>Booked Hours</th><th>Balance</th><th>Exceptions</th></tr></thead><tbody>${techs.map(t=>`<tr><td>${t.name}</td><td>${t.available}</td><td>${t.booked}</td><td>${t.available-t.booked}</td><td>${t.leave}</td></tr>`).join('')}</tbody></table></div>`;}
function labourForecast(){return `<div class="section-head"><h2>Labour Forecast</h2><span class="pill accent">Healthy position +214 hours</span></div><div class="grid grid-3">${kpi('Available Labour','1,248 hrs')}${kpi('Outstanding Job Hours','1,034 hrs')}${kpi('Projected Balance','+214 hrs')}</div><div class="card" style="margin-top:16px"><h3>Management Recommendations</h3><div class="summary-box">Labour is close to the healthy +200 hour position. Keep urgent and Priority 1 jobs protected. Chase outstanding quotes where labour can be absorbed before the end of month.</div></div>`;}
function contracts(){ if(state.tab==='Proposal Generator') return proposal(); if(state.tab==='Customers') return customerList(); if(state.tab==='Dashboard') return contractDashboard(); return `<div class="section-head"><h2>${state.tab}</h2></div><div class="grid grid-3">${kpi('Active Contracts','128')}${kpi('Expiring 90 Days','23')}${kpi('Revenue Under Contract',money(1840000))}</div>`;}
function contractDashboard(){return `<div class="grid grid-4">${kpi('Active Contracts','128')}${kpi('Expiring 30 Days','8')}${kpi('Expiring 90 Days','23')}${kpi('Revenue Under Contract',money(1840000))}</div><div class="grid grid-2" style="margin-top:16px"><div class="card chart-wrap"><h3>Contracts by Customer Value</h3>${barChart(contractCustomers.slice(0,10).map(c=>c.name.split(' ')[0]),contractCustomers.slice(0,10).map(c=>c.value),80000)}</div><div class="card"><h3>Upcoming Renewals</h3><table><tbody>${contractCustomers.slice(0,8).map(c=>`<tr><td>${c.name}</td><td>${c.expiry}</td><td>${money(c.value)}</td></tr>`).join('')}</tbody></table></div></div>`;}
function customerList(){return `<div class="section-head"><h2>Customers</h2><span class="pill">Alphabetical site list</span></div><div class="card"><table><thead><tr><th>Customer</th><th>Site</th><th>Assets</th><th>Contract Value</th><th>Expiry</th></tr></thead><tbody>${contractCustomers.map(c=>`<tr class="clickable" onclick="customerDetail('${c.name}')"><td>${c.name}</td><td>${c.site}</td><td>${c.assets.length}</td><td>${money(c.value)}</td><td>${c.expiry}</td></tr>`).join('')}</tbody></table></div>`;}
function customerDetail(name){const c=contractCustomers.find(x=>x.name===name);openDrawer(name,`<div class="grid grid-3">${kpi('Contract Value',money(c.value))}${kpi('Assets',c.assets.length)}${kpi('Expiry',c.expiry)}</div><div class="card" style="margin-top:16px"><h3>Assets</h3><table><thead><tr><th>ID</th><th>Type</th><th>Location</th><th>Age</th></tr></thead><tbody>${c.assets.map(a=>`<tr><td>${a.id}</td><td>${a.type}</td><td>${a.location}</td><td>${a.age} yrs</td></tr>`).join('')}</tbody></table></div>`);}
function defaultAssets(){ if(!state.assets.length) state.assets=[{type:'Package Unit',qty:4,age:8},{type:'Split System',qty:12,age:4},{type:'Exhaust Fan',qty:8,age:6},{type:'Ducted System',qty:3,age:10}]; }
function proposal(){defaultAssets();return `<div class="section-head"><h2>Proposal Generator</h2><span class="pill">Annual price auto-calculated behind the scenes</span></div><div class="grid grid-2"><div class="card"><h3>Proposal Details</h3><div class="form"><label>Upload Customer Details</label><input type="file" id="customer-upload" accept=".csv,.xlsx"><label>Customer Name</label><input id="proposal-customer" value="Monash Corporate Park"><label>Site Details</label><textarea id="proposal-site">Building A, 22 Corporate Drive, Melbourne VIC</textarea><label>Contract Length</label><select id="contract-length"><option value="1">12 months</option><option value="2">24 months</option><option value="3">36 months</option></select><label>Visit Frequency</label><select id="visit-frequency"><option value="2">Bi-Annual</option><option value="4" selected>Quarterly</option><option value="12">Monthly</option></select><label>Response Time</label><select id="response-time"><option value="1">Standard</option><option value="1.15">Priority</option><option value="1.3">Emergency</option></select></div></div><div class="card"><h3>Asset List</h3><div class="form"><label>Upload Asset List</label><input type="file" id="asset-upload" accept=".csv"></div><p class="kpi-note">Upload a CSV, edit the grid, manually add assets, and download the asset list as CSV.</p><div id="asset-editor"></div><div class="actions"><button class="btn secondary" onclick="addAsset()">Add Asset</button><button class="btn secondary" onclick="downloadAssets()">Download CSV</button></div><div style="height:16px"></div><div class="summary-box"><div class="kpi-label">Calculated Annual Contract Value</div><div id="calculated-price" class="kpi-value">$0</div><p class="kpi-note">Uses hidden pricing rules for asset type, quantity, age, visit frequency, response time, labour allowance and margin.</p></div><div style="height:14px"></div><button class="btn orange" onclick="generateProposal()">Generate Proposal PDF</button></div></div>`;}
function renderAssets(){const el=$('#asset-editor'); if(!el) return; el.innerHTML=state.assets.map((a,i)=>`<div class="asset-row"><select onchange="state.assets[${i}].type=this.value;renderAssets()">${assetRates.map(r=>`<option ${r.type===a.type?'selected':''}>${r.type}</option>`).join('')}</select><input type="number" value="${a.qty}" min="1" onchange="state.assets[${i}].qty=+this.value;renderAssets()"><input type="number" value="${a.age}" min="0" onchange="state.assets[${i}].age=+this.value;renderAssets()"><button class="btn secondary" onclick="state.assets.splice(${i},1);renderAssets()">×</button></div>`).join(''); $('#calculated-price').textContent=money(contractPrice());}
function contractPrice(){const visits=+($('#visit-frequency')?.value||4); const response=+($('#response-time')?.value||1); const length=+($('#contract-length')?.value||1); let base=state.assets.reduce((t,a)=>{const r=assetRates.find(x=>x.type===a.type)||assetRates[0]; const ageRisk=a.age>10?1.22:a.age>6?1.12:1; return t+(r.rate*a.qty*ageRisk*(visits/4));},0); return base*response*1.28*(length>1?.96:1);}
function addAsset(){state.assets.push({type:'Split System',qty:1,age:1});renderAssets();}
function downloadAssets(){const csv='Type,Quantity,Age\n'+state.assets.map(a=>`${a.type},${a.qty},${a.age}`).join('\n'); download(csv,'paramount-asset-list.csv','text/csv');}
function download(content,name,type){const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([content],{type})); a.download=name; a.click(); URL.revokeObjectURL(a.href);}
function generateProposal(){const customer=$('#proposal-customer').value||'Customer'; const price=money(contractPrice()); if(window.jspdf?.jsPDF){const doc=new window.jspdf.jsPDF(); let y=18; doc.setTextColor(14,42,71); doc.setFont('times','normal'); doc.setFontSize(22); doc.text('Paramount Air Maintenance Proposal',14,y); y+=12; doc.setFont('helvetica','normal'); doc.setFontSize(11); doc.text(`Prepared for: ${customer}`,14,y); y+=7; doc.text(`Calculated Annual Contract Value: ${price}`,14,y); y+=12; ['Company profile','Maintenance methodology','Asset register','Visit schedule','Service inclusions','Exclusions','Compliance and safety','Commercial terms','Signature acceptance'].forEach(sec=>{doc.setFontSize(14);doc.text(sec,14,y);y+=7;doc.setFontSize(10);doc.text('Paramount Air provides planned preventative maintenance, asset condition reporting, risk identification, compliance support and responsive HVAC service delivery tailored to the customer site.',14,y,{maxWidth:180});y+=18;if(y>270){doc.addPage();y=18;}}); doc.save(`Paramount-Maintenance-Proposal-${customer.replaceAll(' ','-')}.pdf`);} else {download(`<h1>Paramount Air Maintenance Proposal</h1><p>Prepared for ${customer}</p><p>Annual value: ${price}</p>`,'Paramount-Maintenance-Proposal.html','text/html');}}
function employee(){ if(state.tab==='Calendar') return leaveCalendar(); if(state.tab==='Annual Leave') return annualLeave(); if(state.tab==='Sick Leave') return sickLeave(); if(state.tab==='Apply For Leave') return applyLeave(); return employeeDash(); }
function employeeDash(){return `<div class="grid grid-4">${kpi('Currently On Leave','3')}${kpi('Upcoming Leave','14')}${kpi('Pending Requests','5')}${kpi('Birthdays','2')}</div><div style="height:16px"></div>${leaveCalendar()}`;}
function leaveCalendar(){return `<div class="section-head"><h2>Team Calendar</h2><span class="pill">Annual · Sick · Long Service · Public Holiday</span></div><div class="calendar">${Array.from({length:35},(_,i)=>`<div class="day"><strong>${i<30?i+1:''}</strong>${[3,7,12,18,23,27].includes(i)?`<span class="leave-chip">${leaveEmployees[i%leaveEmployees.length].name} — Annual</span>`:''}${[9,21].includes(i)?`<span class="leave-chip sick">Sick Leave</span>`:''}</div>`).join('')}</div>`;}
function annualLeave(){return `<div class="section-head"><h2>Annual Leave Register</h2><span class="pill">Graphs restored</span></div><div class="grid grid-2"><div class="card chart-wrap"><h3>Leave Entitlement vs Taken</h3>${groupedBars(leaveEmployees.map(e=>e.name.split(' ')[0]),leaveEmployees.map(e=>e.entitlement),leaveEmployees.map(e=>e.taken))}</div><div class="card chart-wrap"><h3>Remaining Annual Leave</h3>${barChart(leaveEmployees.map(e=>e.name.split(' ')[0]),leaveEmployees.map(e=>e.entitlement-e.taken-e.booked),160)}</div></div><div class="card" style="margin-top:16px"><table><thead><tr><th>Employee</th><th>Entitlement</th><th>Taken</th><th>Booked</th><th>Remaining</th></tr></thead><tbody>${leaveEmployees.map(e=>`<tr class="clickable" onclick="openDrawer('${e.name} Leave History')"><td>${e.name}</td><td>${e.entitlement}</td><td>${e.taken}</td><td>${e.booked}</td><td>${e.entitlement-e.taken-e.booked}</td></tr>`).join('')}</tbody></table></div>`;}
function sickLeave(){return `<div class="section-head"><h2>Sick Leave</h2></div><div class="card"><table><thead><tr><th>Employee</th><th>Sick Leave Taken</th><th>Trend</th></tr></thead><tbody>${leaveEmployees.map(e=>`<tr><td>${e.name}</td><td>${e.sick} hrs</td><td>${e.sick>38?'<span class="status-warn">Review pattern</span>':'Normal'}</td></tr>`).join('')}</tbody></table></div>`;}
function applyLeave(){return `<div class="card"><h2>Apply For Leave</h2><div class="form"><label>Request Type</label><select><option>Annual Leave</option><option>Sick Leave</option><option>Carer's Leave</option><option>Long Service Leave</option></select><label>Start Date</label><input type="date"><label>End Date</label><input type="date"><label>Half Day</label><select><option>No</option><option>Morning</option><option>Afternoon</option></select><label>Notes</label><textarea></textarea><label>Attach Document</label><input type="file"><button class="btn orange">Submit Request</button></div></div>`;}
function settings(){return `<div class="card"><h2>Platform Settings</h2><p class="kpi-note">Managers approve leave, generate proposals, edit maintenance contract data and view financials. Admin maintains users and system settings.</p><div class="summary-box">Supabase-ready architecture: customers, sites, contacts, assets, contracts, pricing rules, jobs, quotes, technician activity, leave requests, labour availability and audit logs.</div></div>`;}
function bind(){ const tf=$('#time-filter'); if(tf) tf.onchange=e=>{state.filter=e.target.value;renderScreen();}; const ts=$('#tech-select'); if(ts) ts.onchange=e=>{state.selectedTech=e.target.value;renderScreen();}; ['visit-frequency','response-time','contract-length'].forEach(id=>{const el=$('#'+id); if(el) el.onchange=renderAssets;}); const au=$('#asset-upload'); if(au) au.onchange=e=>{const f=e.target.files[0]; if(!f)return; const r=new FileReader(); r.onload=()=>{state.assets=r.result.split(/\r?\n/).slice(1).filter(Boolean).map(line=>{const [type,qty,age]=line.split(',');return {type:type||'Split System',qty:+qty||1,age:+age||0};});renderAssets();}; r.readAsText(f);}; renderAssets();}
function scale(values,maxOverride){const max=maxOverride||Math.max(...values,1); return v=>260-(v/max)*220;}
function lineChart(labels,values,name){return multiLineChart(labels,[{name,values,cls:'line-main'}]);}
function multiLineChart(labels,series){const all=series.flatMap(s=>s.values); const max=Math.max(...all,1); const sx=i=>50+(i/(labels.length-1||1))*540; const sy=v=>260-(v/max)*220; return `<svg class="svg-chart" viewBox="0 0 640 300"><line x1="44" y1="260" x2="600" y2="260" stroke="rgba(14,42,71,.18)"/><line x1="44" y1="40" x2="44" y2="260" stroke="rgba(14,42,71,.18)"/>${series.map(s=>`<polyline class="${s.cls}" points="${s.values.map((v,i)=>`${sx(i)},${sy(v)}`).join(' ')}"/>`).join('')}${labels.filter((_,i)=>i%Math.ceil(labels.length/6)===0).map((l,i)=>`<text class="axis-label" x="${50+i*100}" y="286">${String(l).slice(0,10)}</text>`).join('')}${series.map((s,i)=>`<text class="bar-label" x="${430}" y="${35+i*18}">${s.name}</text>`).join('')}</svg>`;}
function barChart(labels,values,maxOverride,target){const max=maxOverride||Math.max(...values,1); const w=500/(values.length||1); return `<svg class="svg-chart" viewBox="0 0 640 300"><line x1="44" y1="260" x2="600" y2="260" stroke="rgba(14,42,71,.18)"/>${target?`<line class="line-target" x1="44" y1="${260-(target/max)*220}" x2="600" y2="${260-(target/max)*220}"/><text class="axis-label" x="510" y="${252-(target/max)*220}">Target KPI</text>`:''}${values.map((v,i)=>{const h=(v/max)*220; const x=55+i*w; return `<rect class="${i%3===0?'bar-accent':'bar-main'}" x="${x}" y="${260-h}" width="${Math.max(12,w-12)}" height="${h}" rx="8"/><text class="axis-label" x="${x}" y="286">${String(labels[i]).slice(0,8)}</text>`}).join('')}</svg>`;}
function groupedBars(labels,a,b){const max=Math.max(...a,...b,1); const w=500/(labels.length||1); return `<svg class="svg-chart" viewBox="0 0 640 300"><line x1="44" y1="260" x2="600" y2="260" stroke="rgba(14,42,71,.18)"/>${labels.map((l,i)=>{const x=55+i*w; const h1=(a[i]/max)*220; const h2=(b[i]/max)*220; return `<rect class="bar-main" x="${x}" y="${260-h1}" width="${Math.max(8,w/2-8)}" height="${h1}" rx="7"/><rect class="bar-accent" x="${x+Math.max(10,w/2-3)}" y="${260-h2}" width="${Math.max(8,w/2-8)}" height="${h2}" rx="7"/><text class="axis-label" x="${x}" y="286">${String(l).slice(0,7)}</text>`}).join('')}<text class="bar-label" x="430" y="34">Navy = first measure</text><text class="bar-label" x="430" y="52">Orange = second measure</text></svg>`;}
render();
